version: '3.4'

services:

  # Microsoft SQL Server instance that contains the EPM data.
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file: .env

  # Open Policy Agent (OPA) service that is used as a side-car of EPM Web Server for resource authorization.
  opa:
    image: openpolicyagent/opa
    env_file: .env
    command: run --server --addr :45000

  # EPM Modules

  scripthost:
    image: scripthost
    env_file: .env

  epmserver:
    image: epmserver
    ports:
      - "6516:6516"
    env_file: .env
    depends_on:
      - database
      - scripthost
    
  epmwebserver:
    image: epmwebserver
    env_file: .env
    depends_on:
      - epmserver
      - opa
    extra_hosts:
      - "localhost:192.168.8.3"

  epmnode:
    image: epmnode
    env_file: .env

  epmportal:
    image: epmportal
    env_file: .env
    depends_on:
      - epmwebserver
      - epmnode
    extra_hosts:
      - "localhost:192.168.8.3"

  # Reverse Proxy

  nginx:
    image: nginx
    ports:
      - "8181:8181"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./webserver.crt:/webserver.crt
      - ./webserver.key:/webserver.key